
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 24 13:21:06 GMT 2019
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Dec 24 13:21:06 GMT 2019
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\146\000\002\002\004\000\002\067\002\000\002\002" +
    "\004\000\002\003\006\000\002\004\005\000\002\005\004" +
    "\000\002\006\006\000\002\007\004\000\002\007\003\000" +
    "\002\010\004\000\002\010\003\000\002\011\007\000\002" +
    "\012\003\000\002\012\003\000\002\013\004\000\002\013" +
    "\003\000\002\014\007\000\002\015\003\000\002\015\003" +
    "\000\002\016\012\000\002\020\004\000\002\020\003\000" +
    "\002\021\005\000\002\022\003\000\002\022\003\000\002" +
    "\040\005\000\002\040\003\000\002\023\004\000\002\023" +
    "\003\000\002\024\005\000\002\025\010\000\002\026\004" +
    "\000\002\026\006\000\002\026\003\000\002\036\004\000" +
    "\002\037\003\000\002\037\003\000\002\027\004\000\002" +
    "\027\003\000\002\030\005\000\002\031\012\000\002\032" +
    "\004\000\002\033\004\000\002\033\003\000\002\034\005" +
    "\000\002\035\005\000\002\041\003\000\002\041\005\000" +
    "\002\041\005\000\002\041\005\000\002\041\004\000\002" +
    "\041\005\000\002\041\005\000\002\041\005\000\002\045" +
    "\003\000\002\045\003\000\002\045\004\000\002\045\004" +
    "\000\002\042\005\000\002\042\006\000\002\043\005\000" +
    "\002\044\003\000\002\044\005\000\002\044\003\000\002" +
    "\046\004\000\002\046\003\000\002\047\003\000\002\047" +
    "\003\000\002\047\003\000\002\047\003\000\002\047\003" +
    "\000\002\050\006\000\002\050\007\000\002\051\004\000" +
    "\002\051\004\000\002\052\007\000\002\053\006\000\002" +
    "\054\013\000\002\055\007\000\002\056\003\000\002\056" +
    "\003\000\002\056\003\000\002\057\005\000\002\003\004" +
    "\000\002\055\007\000\002\004\004\000\002\011\006\000" +
    "\002\021\004\000\002\060\002\000\002\064\005\000\002" +
    "\063\003\000\002\063\005\000\002\062\003\000\002\062" +
    "\003\000\002\062\003\000\002\065\003\000\002\065\003" +
    "\000\002\061\003\000\002\061\003\000\002\061\003\000" +
    "\002\017\003\000\002\017\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\317\000\004\023\000\001\002\000\004\002\321\001" +
    "\002\000\004\023\010\001\002\000\004\002\uffff\001\002" +
    "\000\020\002\uffa9\006\uffa9\007\017\017\uffa9\027\uffa9\030" +
    "\uffa9\032\uffa9\001\002\000\004\051\011\001\002\000\022" +
    "\002\uffac\006\uffac\007\uffac\017\uffac\027\uffac\030\uffac\032" +
    "\uffac\043\012\001\002\000\020\002\ufffd\006\ufffd\007\ufffd" +
    "\017\ufffd\027\ufffd\030\ufffd\032\ufffd\001\002\000\010\002" +
    "\uffa9\006\317\017\uffa9\001\002\000\016\002\ufff7\006\ufff7" +
    "\017\ufff7\027\ufff7\030\ufff7\032\ufff7\001\002\000\006\002" +
    "\uffae\017\313\001\002\000\016\002\uffa9\006\uffa9\017\uffa9" +
    "\027\uffa9\030\035\032\uffa9\001\002\000\004\051\020\001" +
    "\002\000\004\050\022\001\002\000\016\002\ufff8\006\ufff8" +
    "\017\ufff8\027\ufff8\030\ufff8\032\ufff8\001\002\000\010\005" +
    "\023\016\025\053\026\001\002\000\046\002\uffa0\006\uffa0" +
    "\014\uffa0\017\uffa0\027\uffa0\030\uffa0\032\uffa0\034\uffa0\036" +
    "\uffa0\041\uffa0\042\uffa0\043\uffa0\044\uffa0\045\uffa0\046\uffa0" +
    "\047\uffa0\051\uffa0\054\uffa0\001\002\000\022\002\uffa9\006" +
    "\uffa9\017\uffa9\027\uffa9\030\uffa9\032\uffa9\042\032\051\020" +
    "\001\002\000\046\002\uff9f\006\uff9f\014\uff9f\017\uff9f\027" +
    "\uff9f\030\uff9f\032\uff9f\034\uff9f\036\uff9f\041\uff9f\042\uff9f" +
    "\043\uff9f\044\uff9f\045\uff9f\046\uff9f\047\uff9f\051\uff9f\054" +
    "\uff9f\001\002\000\046\002\uff9e\006\uff9e\014\uff9e\017\uff9e" +
    "\027\uff9e\030\uff9e\032\uff9e\034\uff9e\036\uff9e\041\uff9e\042" +
    "\uff9e\043\uff9e\044\uff9e\045\uff9e\046\uff9e\047\uff9e\051\uff9e" +
    "\054\uff9e\001\002\000\016\002\ufff5\006\ufff5\017\ufff5\027" +
    "\ufff5\030\ufff5\032\ufff5\001\002\000\016\002\uffab\006\uffab" +
    "\017\uffab\027\uffab\030\uffab\032\uffab\001\002\000\016\002" +
    "\ufff4\006\ufff4\017\ufff4\027\ufff4\030\ufff4\032\ufff4\001\002" +
    "\000\020\002\uffa9\006\uffa9\017\uffa9\027\uffa9\030\uffa9\032" +
    "\uffa9\051\020\001\002\000\016\002\ufff6\006\ufff6\017\ufff6" +
    "\027\ufff6\030\ufff6\032\ufff6\001\002\000\014\002\ufff2\006" +
    "\ufff2\017\ufff2\027\ufff2\032\ufff2\001\002\000\004\051\272" +
    "\001\002\000\014\002\uffa9\006\uffa9\017\uffa9\027\uffa9\032" +
    "\041\001\002\000\012\002\uffec\006\uffec\017\uffec\027\uffec" +
    "\001\002\000\012\002\uffa9\006\uffa9\017\uffa9\027\062\001" +
    "\002\000\004\051\044\001\002\000\016\002\uffa9\006\uffa9" +
    "\017\uffa9\027\uffa9\042\060\051\044\001\002\000\004\043" +
    "\050\001\002\000\006\041\046\043\uffa7\001\002\000\012" +
    "\002\uffed\006\uffed\017\uffed\027\uffed\001\002\000\004\051" +
    "\044\001\002\000\004\043\uffa6\001\002\000\010\004\053" +
    "\013\054\051\052\001\002\000\020\002\uffa8\006\uffa8\017" +
    "\uffa8\027\uffa8\036\uffa8\042\uffa8\051\uffa8\001\002\000\020" +
    "\002\uffa3\006\uffa3\017\uffa3\027\uffa3\036\uffa3\042\uffa3\051" +
    "\uffa3\001\002\000\020\002\uffa5\006\uffa5\017\uffa5\027\uffa5" +
    "\036\uffa5\042\uffa5\051\uffa5\001\002\000\020\002\uffa4\006" +
    "\uffa4\017\uffa4\027\uffa4\036\uffa4\042\uffa4\051\uffa4\001\002" +
    "\000\012\002\uffe9\006\uffe9\017\uffe9\027\uffe9\001\002\000" +
    "\012\002\uffaa\006\uffaa\017\uffaa\027\uffaa\001\002\000\012" +
    "\002\uffea\006\uffea\017\uffea\027\uffea\001\002\000\014\002" +
    "\uffa9\006\uffa9\017\uffa9\027\uffa9\051\044\001\002\000\012" +
    "\002\uffeb\006\uffeb\017\uffeb\027\uffeb\001\002\000\014\002" +
    "\uffa9\006\uffa9\017\uffa9\020\uffa9\022\070\001\002\000\010" +
    "\002\uffe7\006\uffe7\017\uffe7\001\002\000\010\002\ufffb\006" +
    "\ufffb\017\ufffb\001\002\000\012\002\uffa9\006\uffa9\017\uffa9" +
    "\020\113\001\002\000\016\006\uffa9\007\017\017\uffa9\027" +
    "\uffa9\030\uffa9\032\uffa9\001\002\000\012\002\uffe5\006\uffe5" +
    "\017\uffe5\020\uffe5\001\002\000\004\051\073\001\002\000" +
    "\014\002\uffa9\006\uffa9\017\uffa9\020\uffa9\022\070\001\002" +
    "\000\012\002\uffe6\006\uffe6\017\uffe6\020\uffe6\001\002\000" +
    "\004\035\074\001\002\000\010\031\075\036\uffa9\051\uffa9" +
    "\001\002\000\004\051\uffde\001\002\000\006\036\uffe0\051" +
    "\uffdd\001\002\000\004\036\104\001\002\000\004\051\044" +
    "\001\002\000\006\036\uffe2\042\102\001\002\000\010\031" +
    "\075\036\uffa9\051\uffa9\001\002\000\004\036\uffe1\001\002" +
    "\000\004\043\105\001\002\000\016\006\uffe3\007\uffe3\017" +
    "\uffe3\027\uffe3\030\uffe3\032\uffe3\001\002\000\004\017\110" +
    "\001\002\000\014\002\uffe4\006\uffe4\017\uffe4\020\uffe4\022" +
    "\uffe4\001\002\000\004\042\111\001\002\000\014\002\uffdf" +
    "\006\uffdf\017\uffdf\020\uffdf\022\uffdf\001\002\000\016\006" +
    "\uffa9\007\017\017\uffa9\027\uffa9\030\uffa9\032\uffa9\001\002" +
    "\000\004\051\120\001\002\000\010\002\uffdb\006\uffdb\017" +
    "\uffdb\001\002\000\010\002\uffe8\006\uffe8\017\uffe8\001\002" +
    "\000\012\002\uffa9\006\uffa9\017\uffa9\020\113\001\002\000" +
    "\010\002\uffdc\006\uffdc\017\uffdc\001\002\000\004\035\121" +
    "\001\002\000\010\031\075\036\uffa9\051\uffa9\001\002\000" +
    "\004\036\123\001\002\000\004\043\124\001\002\000\006" +
    "\004\126\013\127\001\002\000\004\043\130\001\002\000" +
    "\006\042\uff9d\043\uff9d\001\002\000\006\042\uff9c\043\uff9c" +
    "\001\002\000\016\006\uffd9\007\uffd9\017\uffd9\027\uffd9\030" +
    "\uffd9\032\uffd9\001\002\000\006\006\136\017\uffa9\001\002" +
    "\000\004\017\110\001\002\000\012\002\uffda\006\uffda\017" +
    "\uffda\020\uffda\001\002\000\004\017\uffd8\001\002\000\004" +
    "\017\uffd6\001\002\000\014\012\uffa9\015\144\021\151\024" +
    "\155\051\154\001\002\000\004\017\uffd7\001\002\000\006" +
    "\026\267\055\266\001\002\000\016\002\uffc0\012\uffc0\017" +
    "\uffc0\026\uffc0\055\uffc0\056\uffc0\001\002\000\026\002\uffbd" +
    "\012\uffbd\015\uffbd\017\uffbd\021\uffbd\024\uffbd\026\uffbd\051" +
    "\uffbd\055\uffbd\056\uffbd\001\002\000\004\012\262\001\002" +
    "\000\004\035\247\001\002\000\026\002\uffbc\012\uffbc\015" +
    "\uffbc\017\uffbc\021\uffbc\024\uffbc\026\uffbc\051\uffbc\055\uffbc" +
    "\056\uffbc\001\002\000\004\055\246\001\002\000\026\002" +
    "\uffbb\012\uffbb\015\uffbb\017\uffbb\021\uffbb\024\uffbb\026\uffbb" +
    "\051\uffbb\055\uffbb\056\uffbb\001\002\000\026\002\uffbe\012" +
    "\uffbe\015\uffbe\017\uffbe\021\uffbe\024\uffbe\026\uffbe\051\uffbe" +
    "\055\uffbe\056\uffbe\001\002\000\004\051\236\001\002\000" +
    "\026\002\uffa9\012\uffa9\015\144\017\uffa9\021\151\024\155" +
    "\026\uffa9\051\154\055\uffa9\056\uffa9\001\002\000\026\002" +
    "\uffbf\012\uffbf\015\uffbf\017\uffbf\021\uffbf\024\uffbf\026\uffbf" +
    "\051\uffbf\055\uffbf\056\uffbf\001\002\000\010\035\165\037" +
    "\164\050\226\001\002\000\016\005\023\016\025\025\156" +
    "\035\161\051\163\053\026\001\002\000\016\005\023\016" +
    "\025\025\156\035\161\051\163\053\026\001\002\000\030" +
    "\014\uffd3\034\uffd3\036\uffd3\041\uffd3\042\uffd3\043\uffd3\044" +
    "\uffd3\045\uffd3\046\uffd3\047\uffd3\054\uffd3\001\002\000\016" +
    "\014\220\034\175\045\176\046\201\047\177\054\200\001" +
    "\002\000\016\005\023\016\025\025\156\035\161\051\163" +
    "\053\026\001\002\000\030\014\uffca\034\uffca\036\uffca\041" +
    "\uffca\042\uffca\043\uffca\044\uffca\045\uffca\046\uffca\047\uffca" +
    "\054\uffca\001\002\000\034\014\uffcb\034\uffcb\035\165\036" +
    "\uffcb\037\164\041\uffcb\042\uffcb\043\uffcb\044\uffcb\045\uffcb" +
    "\046\uffcb\047\uffcb\054\uffcb\001\002\000\006\051\211\053" +
    "\212\001\002\000\020\005\023\016\025\025\156\035\161" +
    "\036\uffa9\051\163\053\026\001\002\000\030\014\uffc9\034" +
    "\uffc9\036\uffc9\041\uffc9\042\uffc9\043\uffc9\044\uffc9\045\uffc9" +
    "\046\uffc9\047\uffc9\054\uffc9\001\002\000\030\014\uffc8\034" +
    "\uffc8\036\uffc8\041\uffc8\042\uffc8\043\uffc8\044\uffc8\045\uffc8" +
    "\046\uffc8\047\uffc8\054\uffc8\001\002\000\004\036\uffc2\001" +
    "\002\000\020\034\175\036\uffc4\041\174\045\176\046\201" +
    "\047\177\054\200\001\002\000\004\036\173\001\002\000" +
    "\030\014\uffc5\034\uffc5\036\uffc5\041\uffc5\042\uffc5\043\uffc5" +
    "\044\uffc5\045\uffc5\046\uffc5\047\uffc5\054\uffc5\001\002\000" +
    "\020\005\023\016\025\025\156\035\161\036\uffa9\051\163" +
    "\053\026\001\002\000\016\005\023\016\025\025\156\035" +
    "\161\051\163\053\026\001\002\000\016\005\023\016\025" +
    "\025\156\035\161\051\163\053\026\001\002\000\016\005" +
    "\023\016\025\025\156\035\161\051\163\053\026\001\002" +
    "\000\016\005\023\016\025\025\156\035\161\051\163\053" +
    "\026\001\002\000\016\005\023\016\025\025\156\035\161" +
    "\051\163\053\026\001\002\000\030\014\uffd1\034\uffd1\036" +
    "\uffd1\041\uffd1\042\uffd1\043\uffd1\044\uffd1\045\uffd1\046\uffd1" +
    "\047\uffd1\054\uffd1\001\002\000\030\014\uffcd\034\175\036" +
    "\uffcd\041\uffcd\042\uffcd\043\uffcd\044\uffcd\045\176\046\201" +
    "\047\uffcd\054\uffcd\001\002\000\030\014\uffcc\034\175\036" +
    "\uffcc\041\uffcc\042\uffcc\043\uffcc\044\uffcc\045\176\046\201" +
    "\047\uffcc\054\uffcc\001\002\000\030\014\uffd2\034\175\036" +
    "\uffd2\041\uffd2\042\uffd2\043\uffd2\044\uffd2\045\uffd2\046\201" +
    "\047\uffd2\054\uffd2\001\002\000\030\014\uffce\034\uffce\036" +
    "\uffce\041\uffce\042\uffce\043\uffce\044\uffce\045\uffce\046\uffce" +
    "\047\uffce\054\uffce\001\002\000\004\036\uffc3\001\002\000" +
    "\004\040\215\001\002\000\006\037\164\040\uffa1\001\002" +
    "\000\006\040\uffa2\044\uffa2\001\002\000\004\040\214\001" +
    "\002\000\034\014\uffc6\034\uffc6\036\uffc6\040\uffc6\041\uffc6" +
    "\042\uffc6\043\uffc6\044\uffc6\045\uffc6\046\uffc6\047\uffc6\050" +
    "\uffc6\054\uffc6\001\002\000\034\014\uffc7\034\uffc7\036\uffc7" +
    "\040\uffc7\041\uffc7\042\uffc7\043\uffc7\044\uffc7\045\uffc7\046" +
    "\uffc7\047\uffc7\050\uffc7\054\uffc7\001\002\000\016\034\175" +
    "\036\217\045\176\046\201\047\177\054\200\001\002\000" +
    "\030\014\uffd0\034\uffd0\036\uffd0\041\uffd0\042\uffd0\043\uffd0" +
    "\044\uffd0\045\uffd0\046\uffd0\047\uffd0\054\uffd0\001\002\000" +
    "\004\043\221\001\002\000\016\015\144\021\151\024\155" +
    "\026\uffa9\051\154\055\uffa9\001\002\000\006\026\uffb6\055" +
    "\uffb6\001\002\000\030\014\uffcf\034\uffcf\036\uffcf\041\uffcf" +
    "\042\uffcf\043\uffcf\044\uffcf\045\uffcf\046\uffcf\047\uffcf\054" +
    "\uffcf\001\002\000\004\050\232\001\002\000\004\042\231" +
    "\001\002\000\016\005\023\016\025\025\156\035\161\051" +
    "\163\053\026\001\002\000\016\034\175\042\230\045\176" +
    "\046\201\047\177\054\200\001\002\000\026\002\uffba\012" +
    "\uffba\015\uffba\017\uffba\021\uffba\024\uffba\026\uffba\051\uffba" +
    "\055\uffba\056\uffba\001\002\000\026\002\uffaf\012\uffaf\015" +
    "\uffaf\017\uffaf\021\uffaf\024\uffaf\026\uffaf\051\uffaf\055\uffaf" +
    "\056\uffaf\001\002\000\016\005\023\016\025\025\156\035" +
    "\161\051\163\053\026\001\002\000\016\034\175\042\234" +
    "\045\176\046\201\047\177\054\200\001\002\000\026\002" +
    "\uffb9\012\uffb9\015\uffb9\017\uffb9\021\uffb9\024\uffb9\026\uffb9" +
    "\051\uffb9\055\uffb9\056\uffb9\001\002\000\016\002\uffc1\012" +
    "\uffc1\017\uffc1\026\uffc1\055\uffc1\056\uffc1\001\002\000\004" +
    "\011\237\001\002\000\016\005\023\016\025\025\156\035" +
    "\161\051\163\053\026\001\002\000\016\034\175\044\241" +
    "\045\176\046\201\047\177\054\200\001\002\000\016\005" +
    "\023\016\025\025\156\035\161\051\163\053\026\001\002" +
    "\000\016\034\175\043\243\045\176\046\201\047\177\054" +
    "\200\001\002\000\014\015\144\021\151\024\155\051\154" +
    "\056\uffa9\001\002\000\004\056\245\001\002\000\026\002" +
    "\uffb4\012\uffb4\015\uffb4\017\uffb4\021\uffb4\024\uffb4\026\uffb4" +
    "\051\uffb4\055\uffb4\056\uffb4\001\002\000\026\002\uffb7\012" +
    "\uffb7\015\uffb7\017\uffb7\021\uffb7\024\uffb7\026\uffb7\051\uffb7" +
    "\055\uffb7\056\uffb7\001\002\000\022\005\250\016\025\025" +
    "\156\035\161\036\uffa9\051\163\053\026\057\252\001\002" +
    "\000\016\034\uffa0\036\257\045\uffa0\046\uffa0\047\uffa0\054" +
    "\uffa0\001\002\000\004\036\uffb0\001\002\000\004\036\uffb1" +
    "\001\002\000\004\036\255\001\002\000\016\034\175\036" +
    "\uffb2\045\176\046\201\047\177\054\200\001\002\000\004" +
    "\042\256\001\002\000\026\002\uffb3\012\uffb3\015\uffb3\017" +
    "\uffb3\021\uffb3\024\uffb3\026\uffb3\051\uffb3\055\uffb3\056\uffb3" +
    "\001\002\000\004\042\260\001\002\000\026\002\uffad\012" +
    "\uffad\015\uffad\017\uffad\021\uffad\024\uffad\026\uffad\051\uffad" +
    "\055\uffad\056\uffad\001\002\000\014\015\144\017\uffa9\021" +
    "\151\024\155\051\154\001\002\000\016\005\023\016\025" +
    "\025\156\035\161\051\163\053\026\001\002\000\016\034" +
    "\175\042\264\045\176\046\201\047\177\054\200\001\002" +
    "\000\014\015\uffd4\017\uffd4\021\uffd4\024\uffd4\051\uffd4\001" +
    "\002\000\004\017\uffd5\001\002\000\026\002\uffb8\012\uffb8" +
    "\015\uffb8\017\uffb8\021\uffb8\024\uffb8\026\uffb8\051\uffb8\055" +
    "\uffb8\056\uffb8\001\002\000\004\043\270\001\002\000\014" +
    "\015\144\021\151\024\155\051\154\055\uffa9\001\002\000" +
    "\004\055\uffb5\001\002\000\004\050\274\001\002\000\014" +
    "\002\ufff3\006\ufff3\017\ufff3\027\ufff3\032\ufff3\001\002\000" +
    "\004\033\275\001\002\000\004\037\303\001\002\000\004" +
    "\042\277\001\002\000\016\002\uffa9\006\uffa9\017\uffa9\027" +
    "\uffa9\032\uffa9\051\272\001\002\000\014\002\ufff1\006\ufff1" +
    "\017\ufff1\027\ufff1\032\ufff1\001\002\000\014\002\uffef\006" +
    "\uffef\017\uffef\027\uffef\032\uffef\001\002\000\014\002\ufff0" +
    "\006\ufff0\017\ufff0\027\ufff0\032\ufff0\001\002\000\006\051" +
    "\305\053\212\001\002\000\004\044\306\001\002\000\006" +
    "\040\uffa1\044\uffa1\001\002\000\006\051\305\053\212\001" +
    "\002\000\004\040\310\001\002\000\004\010\311\001\002" +
    "\000\006\004\126\013\127\001\002\000\004\042\uffee\001" +
    "\002\000\004\052\314\001\002\000\004\002\ufffe\001\002" +
    "\000\006\002\ufffc\017\ufffc\001\002\000\006\002\ufff9\017" +
    "\ufff9\001\002\000\016\002\uffa9\015\144\017\uffa9\021\151" +
    "\024\155\051\154\001\002\000\006\002\ufffa\017\ufffa\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\317\000\006\002\003\067\004\001\001\000\002\001" +
    "\001\000\006\003\005\004\006\001\001\000\002\001\001" +
    "\000\012\005\014\006\012\010\015\060\013\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\007\314\060\315\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\013\035\060\033\001\001\000\004\011\020" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\061" +
    "\023\001\001\000\002\001\001\000\010\011\026\012\027" +
    "\060\030\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\011\026\012\032\060\030\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\272\001\001\000\006\020\037" +
    "\060\036\001\001\000\002\001\001\000\006\040\063\060" +
    "\062\001\001\000\010\021\044\063\042\064\041\001\001" +
    "\000\014\021\056\022\055\060\054\063\042\064\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\063\046\001\001\000\002\001\001\000\004\062" +
    "\050\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\021\056\022\060\060\054" +
    "\063\042\064\041\001\001\000\002\001\001\000\012\023" +
    "\064\024\070\025\065\060\066\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\027\114\030\115\031\111\060" +
    "\113\001\001\000\012\005\105\006\012\010\015\060\013" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\023" +
    "\071\024\070\025\065\060\066\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\026\076\037\077\060\075\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\063\042\064\100\001\001\000\002\001\001\000" +
    "\010\026\102\037\077\060\075\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\036\106\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\006\130\010\015\032\131\060\013\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\027\116\030\115\031\111\060\113\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\026\121\037\077\060\075" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\124\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\033\133\060\134\001" +
    "\001\000\004\036\132\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\030\034\136\046\142\047" +
    "\151\050\147\051\152\052\137\053\145\054\141\055\144" +
    "\057\146\060\140\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\035\260" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\026\046\234\047\151\050\147\051\152\052\137\053" +
    "\145\054\141\055\144\057\146\060\140\001\001\000\002" +
    "\001\001\000\006\042\223\043\224\001\001\000\010\041" +
    "\157\045\156\061\161\001\001\000\010\041\222\045\156" +
    "\061\161\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\041\215\045\156\061\161\001\001\000\002\001\001" +
    "\000\006\042\165\043\166\001\001\000\004\065\207\001" +
    "\001\000\014\041\170\044\171\045\156\060\167\061\161" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\041\170\044\206\045\156\060\167\061\161\001" +
    "\001\000\010\041\205\045\156\061\161\001\001\000\010" +
    "\041\204\045\156\061\161\001\001\000\010\041\203\045" +
    "\156\061\161\001\001\000\010\041\202\045\156\061\161" +
    "\001\001\000\010\041\201\045\156\061\161\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\042\212\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\026\046\221" +
    "\047\151\050\147\051\152\052\137\053\145\054\141\055" +
    "\144\057\146\060\140\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\041" +
    "\226\045\156\061\161\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\041\232\045\156\061" +
    "\161\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\041\237\045\156\061" +
    "\161\001\001\000\002\001\001\000\010\041\241\045\156" +
    "\061\161\001\001\000\002\001\001\000\026\046\243\047" +
    "\151\050\147\051\152\052\137\053\145\054\141\055\144" +
    "\057\146\060\140\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\041\253\045\156\056\252" +
    "\060\250\061\161\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\046\264\047\151\050\147\051\152" +
    "\052\137\053\145\054\141\055\144\057\146\060\140\001" +
    "\001\000\010\041\262\045\156\061\161\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\046\270\047\151\050\147" +
    "\051\152\052\137\053\145\054\141\055\144\057\146\060" +
    "\140\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\275\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\014\301\015\277\060\300\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\065\303\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\065\306\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\311\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\026\046\317\047\151\050\147\051\152\052\137" +
    "\053\145\054\141\055\144\057\146\060\140\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	
	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();

	public String informa(int id_error){
	    switch(id_error){
	    	case 0: 
	    		return "Te ha faltado poner la clausula final de un programa principal(fin.)"; 
	        case 1: 
	            return "Faltan dos puntos verticales en la cabecera del programa principal"; 
	         case 2: 
	         	return "no se debe intruducir cierto o falso en un sentencia escribir"; 
	         case 3: 
	         	return "Te ha faltado poner punto y coma en la seccion declarativa de CONSTANTES, concretamente, en la linea "; 
	         case 4: 
	          	return "Te ha faltado poner punto y coma en la seccion declarativa de VARIABLES, en alguna de sus sentencias ";
	        default: 
	        	return "error desconocido"; 
	    
	    }
	}
	

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // tipo_primitivo ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_primitivo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // tipo_primitivo ::= BOOLEANO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_primitivo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // valor_asignable ::= NUMEROENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor_asignable",47, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // valor_asignable ::= FALSO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor_asignable",47, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // valor_asignable ::= CIERTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor_asignable",47, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // indice_vector ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("indice_vector",51, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // indice_vector ::= NUMEROENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("indice_vector",51, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // tipo_dato ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",48, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // tipo_dato ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",48, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // tipo_dato ::= BOOLEANO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_dato",48, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // listado_ids ::= IDENTIFICADOR COMA listado_ids 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listado_ids",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // listado_ids ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listado_ids",49, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // listado_ids_con_tipo ::= listado_ids DOSPUNTOSVERTICALES tipo_dato 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listado_ids_con_tipo",50, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // cadena_vacia ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cadena_vacia",46, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // declaracion_var ::= listado_ids_con_tipo nueva_lista 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxFatalError(informa(4)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_var",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // declaracion_cte ::= IDENTIFICADOR IGUAL valor_asignable nueva_cte 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 syntaxErrorManager.syntaxFatalError(informa(3)+ id.getLine()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_cte",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // cabecera_programa ::= PROGRAMA IDENTIFICADOR 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxFatalError(informa(1)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera_programa",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // instruccion_salida ::= ESCRIBIR PARENIZQ CIERTO PARENDER PUNTOCOMA 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxFatalError(informa(2));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_salida",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // axiom ::= cabecera_programa cuerpo_programa 
            {
              Axiom RESULT =null;
		 syntaxErrorManager.syntaxFatalError(informa(0)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // llamada_procedimiento ::= IDENTIFICADOR llamada_funcion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamada_procedimiento",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // parametro_salida ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro_salida",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // parametro_salida ::= CADENATEXTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro_salida",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // parametro_salida ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro_salida",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // instruccion_salida ::= ESCRIBIR PARENIZQ parametro_salida PARENDER PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_salida",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // instruccion_para ::= PARA IDENTIFICADOR EN expresion DOSPUNTOSHORIZONTALES expresion DOSPUNTOSVERTICALES bloque_instrucciones FINPARA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_para",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // condicion_doble ::= condicion_simple SINO DOSPUNTOSVERTICALES bloque_instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion_doble",41, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // condicion_simple ::= SI expresion ENTONCES DOSPUNTOSVERTICALES bloque_instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion_simple",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // instruccion_condicional ::= condicion_doble FINALCONDICIONAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_condicional",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // instruccion_condicional ::= condicion_simple FINALCONDICIONAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_condicional",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // instruccion_asignacion ::= IDENTIFICADOR acceso_vector IGUAL expresion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_asignacion",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // instruccion_asignacion ::= IDENTIFICADOR IGUAL expresion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_asignacion",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // nueva_instruccion ::= llamada_procedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_instruccion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // nueva_instruccion ::= instruccion_salida 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_instruccion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // nueva_instruccion ::= instruccion_para 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_instruccion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // nueva_instruccion ::= instruccion_asignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_instruccion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // nueva_instruccion ::= instruccion_condicional 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_instruccion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // bloque_instrucciones ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque_instrucciones",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // bloque_instrucciones ::= nueva_instruccion bloque_instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque_instrucciones",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // lista_argumentos ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_argumentos",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // lista_argumentos ::= expresion COMA lista_argumentos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_argumentos",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // lista_argumentos ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_argumentos",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // llamada_funcion ::= PARENIZQ lista_argumentos PARENDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamada_funcion",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // acceso_vector ::= CORCHEIZQ IDENTIFICADOR acceso_vector CORCHEDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("acceso_vector",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // acceso_vector ::= CORCHEIZQ indice_vector CORCHEDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("acceso_vector",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // valor_atomico ::= IDENTIFICADOR llamada_funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor_atomico",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // valor_atomico ::= IDENTIFICADOR acceso_vector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor_atomico",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // valor_atomico ::= valor_asignable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor_atomico",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // valor_atomico ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor_atomico",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= expresion CONDICIONIGUAL expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= expresion YLOGICO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= NO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= PARENIZQ expresion PARENDER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= expresion PRODUCTO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= valor_atomico 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_devolver ::= DEVOLVER expresion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_devolver",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // bloque_control_devolver ::= bloque_instrucciones instruccion_devolver bloque_instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque_control_devolver",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // seccion_instru_funcion ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_instru_funcion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // seccion_instru_funcion ::= COMIENZO bloque_control_devolver 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_instru_funcion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // cuerpo_funcion ::= seccion_declarativa seccion_instru_funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo_funcion",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // cabecera_funcion ::= FUNCION IDENTIFICADOR PARENIZQ lista_parametros PARENDER DOSPUNTOSVERTICALES tipo_primitivo DOSPUNTOSVERTICALES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera_funcion",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // nueva_funcion ::= cabecera_funcion cuerpo_funcion fin_de_subprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_funcion",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // seccion_funciones ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_funciones",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // seccion_funciones ::= nueva_funcion seccion_funciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_funciones",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // paso_parametro ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("paso_parametro",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // paso_parametro ::= VAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("paso_parametro",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // fin_de_subprograma ::= FIN PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("fin_de_subprograma",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_parametros ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_parametros ::= paso_parametro listado_ids_con_tipo PUNTOCOMA lista_parametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // lista_parametros ::= paso_parametro listado_ids_con_tipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_parametros",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cabecera_procedimiento ::= PROCEDIMIENTO IDENTIFICADOR PARENIZQ lista_parametros PARENDER DOSPUNTOSVERTICALES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera_procedimiento",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // nuevo_procedimiento ::= cabecera_procedimiento cuerpo_programa fin_de_subprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nuevo_procedimiento",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // seccion_procedimientos ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_procedimientos",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // seccion_procedimientos ::= nuevo_procedimiento seccion_procedimientos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_procedimientos",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // subseccion_subprogramas ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_subprogramas",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // subseccion_subprogramas ::= SUBPROGRAMAS seccion_procedimientos seccion_funciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_subprogramas",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // nueva_lista ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_lista",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // nueva_lista ::= declaracion_var 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_lista",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracion_var ::= listado_ids_con_tipo PUNTOCOMA nueva_lista 
            {
              Object RESULT =null;
		int idcomaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int idcomaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Token idcoma = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_var",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // subseccion_var ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_var",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // subseccion_var ::= VARIABLES declaracion_var 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_var",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo_complejo ::= VECTOR CORCHEIZQ indice_vector DOSPUNTOSHORIZONTALES indice_vector CORCHEDER DE tipo_primitivo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_complejo",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // nuevo_tipo ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nuevo_tipo",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // nuevo_tipo ::= declaracion_tipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nuevo_tipo",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declaracion_tipo ::= IDENTIFICADOR IGUAL tipo_complejo PUNTOCOMA nuevo_tipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_tipo",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // subseccion_tipos ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_tipos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // subseccion_tipos ::= TIPOS declaracion_tipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_tipos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // nueva_cte ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_cte",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // nueva_cte ::= declaracion_cte 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nueva_cte",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracion_cte ::= IDENTIFICADOR IGUAL valor_asignable PUNTOCOMA nueva_cte 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion_cte",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // subseccion_ctes ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_ctes",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // subseccion_ctes ::= CONSTANTES declaracion_cte 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("subseccion_ctes",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccion_instrucciones ::= cadena_vacia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_instrucciones",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // seccion_instrucciones ::= COMIENZO bloque_instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_instrucciones",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // seccion_declarativa ::= subseccion_ctes subseccion_tipos subseccion_var subseccion_subprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion_declarativa",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // cuerpo_programa ::= seccion_declarativa seccion_instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo_programa",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // cabecera_programa ::= PROGRAMA IDENTIFICADOR DOSPUNTOSVERTICALES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabecera_programa",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= cabecera_programa cuerpo_programa FIN PUNTO 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		// Para la entrega de febrero pueden comentarse las dos sentencias siguientes:
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);
  		// En caso de no comentarse las sentencias anteriores puede generar una excepcion
  		// en las llamadas a cupTest en la entrega de Febrero. Esto es debido a que 
  		// aún no se tendrá implementada la generación de código intermedio ni final.
  		// Para la entrega de Junio deberán descomentarse y usarse.
  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",53, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

