
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 24 13:21:06 GMT 2019
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIPOS = 22;
  public static final int DE = 6;
  public static final int DEVOLVER = 8;
  public static final int SUBPROGRAMAS = 21;
  public static final int DOSPUNTOSHORIZONTALES = 34;
  public static final int PROGRAMA = 17;
  public static final int ENTERO = 9;
  public static final int SI = 18;
  public static final int CONDICIONIGUAL = 42;
  public static final int FUNCION = 14;
  public static final int CIERTO = 3;
  public static final int PARENIZQ = 27;
  public static final int ENTONCES = 10;
  public static final int PUNTOCOMA = 32;
  public static final int FIN = 13;
  public static final int COMILLASDOBLE = 46;
  public static final int NUMEROENTERO = 41;
  public static final int IDENTIFICADOR = 39;
  public static final int COMIENZO = 4;
  public static final int IGUAL = 38;
  public static final int SINO = 20;
  public static final int FINPARA = 44;
  public static final int CONSTANTES = 5;
  public static final int ESCRIBIR = 11;
  public static final int PROCEDIMIENTO = 16;
  public static final int SUMA = 35;
  public static final int DOSPUNTOSVERTICALES = 33;
  public static final int CORCHEIZQ = 29;
  public static final int EOF = 0;
  public static final int PRODUCTO = 36;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int MENOR = 37;
  public static final int PARENDER = 28;
  public static final int VECTOR = 25;
  public static final int EN = 7;
  public static final int FINALCONDICIONAL = 43;
  public static final int NO = 19;
  public static final int PUNTO = 40;
  public static final int VARIABLES = 24;
  public static final int CADENATEXTO = 45;
  public static final int FALSO = 12;
  public static final int YLOGICO = 26;
  public static final int BOOLEANO = 2;
  public static final int CORCHEDER = 30;
  public static final int PARA = 15;
  public static final int VAR = 23;
}

